#ifndef PCB_H
#define PCB_H

#define HW_TS13

#define	HW_HSE_ENABLED 1 // HSE crystal 8MHz assembled 

#define HW_LED1_BIT   (9)
#define HW_LED1_PORT  GPIOA
#define HW_LED1_INIT  GPIO_PIN_INIT(HW_LED1_PORT, HW_LED1_BIT, GPIO_MODE_OUTPUT)
#define HW_LED1_ON    GPIO_BIT_SET(HW_LED1_PORT, HW_LED1_BIT)
#define HW_LED1_OFF   GPIO_BIT_CLR(HW_LED1_PORT, HW_LED1_BIT) 

#define HW_BUTTON_BIT      (3)
#define HW_BUTTON_PORT     GPIOH
#define HW_BUTTON_INIT     GPIO_PIN_INIT(HW_BUTTON_PORT,HW_BUTTON_BIT,GPIO_MODE_INPUT)
#define HW_BUTTON_PRESSED  GPIO_IN(HW_BUTTON_PORT,HW_BUTTON_BIT)

#define HW_LED2_ON
#define HW_LED2_OFF

// LPUART1 == ui
#define HW_UART1_ON 1
#define	HW_UART1_RX_BIT  3
#define	HW_UART1_RX_PORT GPIOA
#define	HW_UART1_TX_BIT  2
#define	HW_UART1_TX_PORT GPIOA
#define	HW_UART1_GPIO_EN RCC_AHB2ENR1_GPIOAEN

#define HW_CONSOLE_ON_UART
#define	HW_TTY_UART_GETCHAR() uart1_getchar()
#define	HW_TTY_UART_PUTCHAR(ch) uart1_putchar(ch)
#define	HW_TTY_UART_INIT(baud) uart1_init(baud)

// HW SPI support
#define SPI1_ON  1

#define HW_SPI_SW_CS_BIT    (4)
#define HW_SPI_SW_CS_PORT   GPIOA
#define HW_SPI_SW_CS_INIT   GPIO_PIN_INIT(HW_SPI_SW_CS_PORT, HW_SPI_SW_CS_BIT, GPIO_MODE_OUTPUT)
#define HW_SPI_SW_CS_UP     GPIO_BIT_SET(HW_SPI_SW_CS_PORT,HW_SPI_SW_CS_BIT)
#define HW_SPI_SW_CS_DOWN   GPIO_BIT_CLR(HW_SPI_SW_CS_PORT,HW_SPI_SW_CS_BIT)

// output enable (level shifter enable)
#define HW_SPI_OE_INIT      // GPIO_PIN_INIT(HW_SPI_OE_PORT,HW_SPI_OE_BIT,GPIO_MODE_OUTPUT)
#define HW_SPI_OE_ENABLE    // GPIO_BIT_SET(HW_SPI_OE_PORT,HW_SPI_OE_BIT)
#define HW_SPI_OE_DISABLE   // GPIO_BIT_CLR(HW_SPI_OE_PORT,HW_SPI_OE_BIT)

// Target GPO reading
#define HW_GPO_IN_BIT      (0)
#define HW_GPO_IN_PORT     GPIOB
#define HW_GPO_IN_INIT     GPIO_PIN_INIT(HW_GPO_IN_PORT,HW_GPO_IN_BIT,GPIO_MODE_INPUT)
#define HW_GPO_IN          GPIO_IN(HW_GPO_IN_PORT,HW_GPO_IN_BIT)

// VCC power switch
#define HW_CHIP_PWR_BIT     (0)
#define HW_CHIP_PWR_PORT    GPIOA
#define HW_CHIP_PWR_INIT    GPIO_PIN_INIT(HW_CHIP_PWR_PORT, HW_CHIP_PWR_BIT, GPIO_MODE_OUTPUT)
#define HW_CHIP_PWR_ON      GPIO_BIT_SET(HW_CHIP_PWR_PORT, HW_CHIP_PWR_BIT)
#define HW_CHIP_PWR_OFF     GPIO_BIT_CLR(HW_CHIP_PWR_PORT, HW_CHIP_PWR_BIT)


#define HW_USB_DP_BIT   (12)
#define HW_USB_DP_PORT  GPIOA

#endif // PCB_H

